
MODELO = "gpt-5.1-2025-11-13"
MODELO_MINI = "gpt-4.1-mini"
MODELO_TRANSCRIBE = "gpt-4o-mini-transcribe"
MODELO_TEXTO_AUDIO = "gpt-4o-mini-tts"
CHUNCKS_POR_LIBRO = 8
OVERLAP = 5
CHUNK_LIBRO = 300

MIN_TEXTO_POR_PAGINA = 20